# Generated by Django 4.1.7 on 2023-04-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gamen',
            new_name='game_n',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='playern',
            new_name='player_n',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gamen',
            new_name='game_n',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playern',
            new_name='player_n',
        ),
    ]
