# Generated by Django 4.1.7 on 2023-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_gamen_games_game_n_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_n',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
